### ISSUE TITLE
Leaks between namespaces in CI?

### ISSUE THREAD

**Issue by trisberg** [projectriff-archive/function-controller#10]
We have a situation in CI where we have multiple versions of the function controller running in separate namespaces. It looks like a function deployment gets picked up by the wrong function controller in a different namespace from where the function is deployed and then deployed into the namespace where the function was deployed but with the config parameters set to match that of the other namespace where the rogue function-controller was running.

The rogue function-controller is running image `riffci/function-controller:0.0.0-pr26` with the following config:

```
Name:           m-rifffctrl-000pr26-659780-rifffctrl-function-controller-52wc4l
Namespace:      m-rifffctrl-000pr26-659780
Node:           gke-k8s-ci-default-pool-d7ac1668-d52q/10.138.0.3
Containers:
  rifffctrl-function-controller:
    Container ID:   docker://e85a6b4891237f0e67ead356008a9c1b0ac80177145418062a6f904e9085db2a
    Image:          riffci/function-controller:0.0.0-pr26
    Environment:
      SERVER_PORT:                                8080
      JAVA_TOOL_OPTIONS:                          -Xmx512m
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:   m-rifffctrl-000pr26-659780-rifffctrl-kafka:9092
      SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES:  m-rifffctrl-000pr26-659780-rifffctrl-zookeeper:2181
      RIFF_FUNCTION_SIDECAR_TAG:                  0.0.3-build.12
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from m-rifffctrl-000pr26-659780-rifffctrl-sa-token-b2jnf (ro)
```

The deployment for the square function has the following config:

```
Name:                   square
Namespace:              m-riff-003-008187
Pod Template:
  Labels:  function=square
  Containers:
   main:
    Image:        trisberg/square:0.0.1
    Port:         <none>
    Environment:  <none>
    Mounts:       <none>
   sidecar:
    Image:  projectriff/function-sidecar:0.0.3-build.12
    Port:   <none>
    Args:
      --inputs
      square
      --outputs
      replies
      --group
      square
      --protocol
      http
      --brokers
      m-rifffctrl-000pr26-659780-rifffctrl-kafka:9092
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
```

Note the `Image` and `--brokers` settings which come from the function-controller in the `m-rifffctrl-000pr26-659780` namespace instead of the function-controller in the `m-riff-003-008187` namespace. That function-controller has the following config:

```
Name:           m-riff-003-008187-riff-function-controller-688dfff58b-kv8sj
Namespace:      m-riff-003-008187
Node:           gke-k8s-ci-default-pool-d7ac1668-dx8s/10.138.0.2
Containers:
  riff-function-controller:
    Container ID:   docker://1870dc0a2e048817f183159a091b753612a9e7c8bf09a40fecfd729b5ed5ac75
    Image:          projectriff/function-controller:0.0.4-build.3
    Image ID:       docker-pullable://projectriff/function-controller@sha256:f26e341ad42bd15a97ff27f9a25314edf153ce18b2d0531cfc10447ca1bf6e2b
    Port:           8080/TCP
    State:          Running
      Started:      Fri, 26 Jan 2018 18:10:04 -0500
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/health delay=60s timeout=5s period=15s #success=1 #failure=3
    Readiness:      http-get http://:8080/health delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:
      KAFKA_BROKERS:              m-riff-003-008187-riff-kafka:9092
      RIFF_FUNCTION_SIDECAR_TAG:  0.0.4-build.3
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from m-riff-003-008187-riff-sa-token-wps4f (ro)
```

This all looks correct, except for the fact that the deployed function uses config values from the wrong namespace and can't connect to the Kafka broker.

**Comment by ericbottard** [comment]
The current behavior is for the function-controller (whatever its namespace) to monitor *any* namespace for functions and create deployments in the namespace of the function definition.
So obviously, if there are 2 FCs (in two controllers) they will step on each other's toes

I don't know what the traditional behavior for "controller-like" components is:
- should it be entirely confined in one ns and only monitor (and create) stuff there
- or should it be "a singleton"* and be responsible for functions system wide?

\* obviously, this seems to imply that we're not really good with HA setup yet.

**Comment by trisberg** [comment]
I would expect the function controller to ignore functions created in other namespaces since they should be handled by the controller in the same namespace so it can provide the proper configuration settings. 

It seems we got this for free when we used the fabric8 client since this was never an issue before and we have been using multiple namespaces for CI for quite a while.

**Comment by trisberg** [comment]
With the namespace changes to the cli and running a single riff instance on a cluster this is no longer an issue.
