### ISSUE TITLE
update kafka and zookeeper env var names

### ISSUE THREAD

**Issue by markfisher** [projectriff-archive/function-controller#4]
e.g. `SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS` should just be `KAFKA_BROKERS`

**Comment by ericbottard** [comment]
Should be `-brokers` command line arg, if you ask me

**Comment by ericbottard** [comment]
> Should be -brokers command line arg, if you ask me

With the caveat that ENV_VARS can use EnvFromSource, while args cannot...
