### ISSUE TITLE
subscribe to metrics for scaling instead of direct kafka events

### ISSUE THREAD

**Issue by markfisher** [projectriff-archive/function-controller#7]
rather than subscribing directly to the kafka-specific offset topic, we can track the delta between producers and consumers at the sidecar/http-gateway level (including when consumers are activated/deactivated) to drive the scaling algorithm

**Comment by jldec** [comment]
counterpart to sidecar metrics publisher https://github.com/projectriff/function-sidecar/issues/41

**Comment by jldec** [comment]
This work should fix current overscaling behavior observed during kafka rebalancing pauses.

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#322
